# https://github.com/babel/babel-eslint
parser: babel-eslint
env:
  browser: true
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  import/no-unresolved: [2, {commonjs: true, amd: true}]
    import/named: 2
    import/namespace: 2
    import/default: 2
    import/export: 2

  no-console: 0
    #import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
}

  plugins:
    # https://github.com/jest-community/eslint-plugin-jest
    - jest
    # https://github.com/babel/eslint-plugin-babel
    - babel
    - import